gravitee-plugin-fetcher/src/main/java/io/gravitee/plugin/fetcher/internal/FetcherPluginHandler.java
gravitee-plugin-service-discovery/src/main/java/io/gravitee/plugin/discovery/internal/ServiceDiscoveryPluginHandler.java

Close the URLClassLoader used to load the plugin class after loading it.
fixes https://github.com/gravitee-io/issues/issues/2920

Close URLClassLoader after usage.

---

gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/api/PluginManifestFactory.java
gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/internal/PluginFactory.java
gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/internal/PluginImpl.java
gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/internal/PluginRegistryImpl.java
gravitee-plugin-policy/src/main/java/io/gravitee/plugin/policy/internal/PolicyPluginHandler.java

**Issue
https://github.com/gravitee-io/issues/issues/7600
Description
Open the API so that the SDK is able to work with PluginManifest and PluginEventListener to take benefit from initialization phase of a policy plugin (PolicyContext.onActivation() needed by JavascriptPolicy for example)
@jhaeyaert, not a big fan of rising the visibility for PluginImpl since its in the internal package.
Maybe we can discuss that point.**
---
- use it directly by updating your project with version: `1.23.2-issues-7600-it-test-subclasses-2-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravit …

fix: open design of plugin instantiation

---

.circleci/config.yml
gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/api/AbstractConfigurablePluginManager.java
gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/api/ConfigurablePluginManager.java
gravitee-plugin-core/src/test/java/io/gravitee/plugin/core/api/AbstractConfigurablePluginManagerTest.java
gravitee-plugin-core/src/test/resources/files/docs/doc.md
gravitee-plugin-core/src/test/resources/files/schemas/schema-form.json
gravitee-plugin-core/src/test/resources/files/schemas/subfolder_1/schema-form.json
gravitee-plugin-core/src/test/resources/files/schemas/subfolder_1/subfolder_2/schema-form.json

**Issue**
https://graviteecommunity.atlassian.net/browse/APIM-189
Add capability to retrieve subscription schema form under `schemas/subscriptions`.
As for `getSchema` (which is looking in `schemas` folder), the first file is returned.
---
- use it directly by updating your project with version: `1.25.0-apim-189-entrypoint-subscription-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/plugin/gravitee-plugin/1.25.0-apim-189-entrypoint-subscription-SNAPSHOT/gravitee-plugin-1.25.0-apim-189-entrypoint-subscription-SNAPSHOT.zip)

feat: add deeper file search (in subfolders)

---

gravitee-plugin-fetcher/src/main/java/io/gravitee/plugin/fetcher/internal/FetcherPluginHandler.java

**Issue**
Add a type to the FetcherPluginHandler. Without any type, nobody was able to deactivate a fetcher with an env variable that looks like: `gravitee_fetchers_gitfetcher_enabled:false`
---
- use it directly by updating your project with version: `1.24.2-add-type-to-fetcher-plugins-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/plugin/gravitee-plugin/1.24.2-add-type-to-fetcher-plugins-SNAPSHOT/gravitee-plugin-1.24.2-add-type-to-fetcher-plugins-SNAPSHOT.zip)

Add a type to the FetcherPluginHandler

---

gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/api/AbstractConfigurablePluginManager.java
gravitee-plugin-core/src/test/java/io/gravitee/plugin/core/api/AbstractConfigurablePluginManagerTest.java

**Issue**
A small description of what you did in that PR.
---
- use it directly by updating your project with version: `1.26.1-fix-icon-loading-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/plugin/gravitee-plugin/1.26.1-fix-icon-loading-SNAPSHOT/gravitee-plugin-1.26.1-fix-icon-loading-SNAPSHOT.zip)

fix: return null if file not found instead of Exception

---

gravitee-plugin-alert/pom.xml
gravitee-plugin-api/pom.xml
gravitee-plugin-cockpit/pom.xml
gravitee-plugin-connector/pom.xml
gravitee-plugin-core/pom.xml
gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/api/PluginType.java
gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/internal/PluginEventListener.java
gravitee-plugin-fetcher/pom.xml
gravitee-plugin-identityprovider/pom.xml
gravitee-plugin-notifier/pom.xml
gravitee-plugin-policy/pom.xml
gravitee-plugin-repository/pom.xml
gravitee-plugin-resource/pom.xml
gravitee-plugin-service-discovery/pom.xml
pom.xml

https://gravitee.atlassian.net/browse/ARCHI-217
https://gravitee.atlassian.net/browse/ARCHI-230
Support new type of plugin
---
- use it directly by updating your project with version: `1.27.0-archi-230-cluster-plugin-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/plugin/gravitee-plugin/1.27.0-archi-230-cluster-plugin-SNAPSHOT/gravitee-plugin-1.27.0-archi-230-cluster-plugin-SNAPSHOT.zip)

Archi 230: add new plugin type for cluster

---

pom.xml

see https://github.com/gravitee-io/gravitee-common/pull/101
This is to avoid this error when apim starts
```
{
"timestamp": "2023-09-13T15:40:54.667Z",
"level": "ERROR",
"thread": "graviteeio-node",
"logger": "io.gravitee.plugin.core.internal.PluginContextFactoryImpl",
"message": "Unable to refresh plugin context",
"context": "default",
"exception": "[...] Caused by: java.lang.NoClassDefFoundError: io/gravitee/common/templating/FreeMarkerComponent [...]",
}
```
---
- use it directly by updating your project with version: `2.0.3-fix-bump-gravitee-common-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.c …

fix: bump gravitee-common to 3.3.3

---

CHANGELOG.md
gravitee-plugin-alert/pom.xml
gravitee-plugin-api/pom.xml
gravitee-plugin-cockpit/pom.xml
gravitee-plugin-connector/pom.xml
gravitee-plugin-core/pom.xml
gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/internal/PluginEventListener.java
gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/spring/PluginConfiguration.java
gravitee-plugin-core/src/test/java/io/gravitee/plugin/core/internal/PluginEventListenerTest.java
gravitee-plugin-fetcher/pom.xml
gravitee-plugin-identityprovider/pom.xml
gravitee-plugin-notifier/pom.xml
gravitee-plugin-policy/pom.xml
gravitee-plugin-repository/pom.xml
gravitee-plugin-resource/pom.xml
gravitee-plugin-service-discovery/pom.xml
pom.xml

**Issue**
https://gravitee.atlassian.net/browse/ARCHI-222
Setup secret-provider to be first in the loading order
---
- use it directly by updating your project with version: `2.1.0-archi-222-secret-managers-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/plugin/gravitee-plugin/2.1.0-archi-222-secret-managers-SNAPSHOT/gravitee-plugin-2.1.0-archi-222-secret-managers-SNAPSHOT.zip)

ARCHI-222 secret managers: plugin load ordering update

---

gravitee-plugin-alert/pom.xml
gravitee-plugin-annotation-processors/pom.xml
gravitee-plugin-api/pom.xml
gravitee-plugin-cockpit/pom.xml
gravitee-plugin-connector/pom.xml
gravitee-plugin-core/pom.xml
gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/api/PluginRegistry.java
gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/internal/PluginRegistryImpl.java
gravitee-plugin-core/src/test/java/io/gravitee/plugin/core/internal/PluginRegistryTest.java
gravitee-plugin-fetcher/pom.xml
gravitee-plugin-identityprovider/pom.xml
gravitee-plugin-notifier/pom.xml
gravitee-plugin-policy/pom.xml
gravitee-plugin-repository/pom.xml
gravitee-plugin-resource/pom.xml
gravitee-plugin-service-discovery/pom.xml
pom.xml

**Issue**
https://gravitee.atlassian.net/browse/ARCHI-143
This PR adds a way to get a plugin by ID from the plugin registry.
---
- use it directly by updating your project with version: `2.2.0-archi-143-add-get-plugin-by-id-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/plugin/gravitee-plugin/2.2.0-archi-143-add-get-plugin-by-id-SNAPSHOT/gravitee-plugin-2.2.0-archi-143-add-get-plugin-by-id-SNAPSHOT.zip)

feat: add way to get plugin by id from plugin registry

---

gravitee-plugin-annotation-processors/pom.xml
gravitee-plugin-annotation-processors/src/main/resources/templates/evaluatorHeader.mustache
gravitee-plugin-annotation-processors/src/test/java/io/gravitee/gateway/reactive/api/context/ExecutionContext.java
gravitee-plugin-annotation-processors/src/test/java/io/gravitee/plugin/annotation/processor/ConfigurationEvaluatorGeneratedTest.java
gravitee-plugin-annotation-processors/src/test/java/io/gravitee/plugin/annotation/processor/result/KeyStore.java
gravitee-plugin-annotation-processors/src/test/java/io/gravitee/plugin/annotation/processor/result/SecurityConfiguration.java
gravitee-plugin-annotation-processors/src/test/java/io/gravitee/plugin/annotation/processor/result/Ssl.java
gravitee-plugin-annotation-processors/src/test/java/io/gravitee/plugin/annotation/processor/result/TrustStore.java
gravitee-plugin-annotation-processors/src/test/resources/test/TestConfigurationEvaluator.java

Creating a new configuration based on the default constructor led to inconsistency when the class does not define default values.
To prevent that, we are cloning the configuration provided at the beginning of the evaluator.
---
- use it directly by updating your project with version: `2.2.1-fix-annotation-processor-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/plugin/gravitee-plugin/2.2.1-fix-annotation-processor-SNAPSHOT/gravitee-plugin-2.2.1-fix-annotation-processor-SNAPSHOT.zip)

fix: clone configuration instead of creating a new one

---

pom.xml

**Issue**
https://gravitee.atlassian.net/browse/ARCHI-296
apply bom v7
---
- use it directly by updating your project with version: `3.1.0-archi-296-upgrade-bom-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/plugin/gravitee-plugin/3.1.0-archi-296-upgrade-bom-SNAPSHOT/gravitee-plugin-3.1.0-archi-296-upgrade-bom-SNAPSHOT.zip)

feat: use latest bom version

---

pom.xml

BREAKING CHANGE: this requires to use latest cockpit connector plugin
---
- use it directly by updating your project with version: `4.0.0-upgrade-cockpit-connector-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/plugin/gravitee-plugin/4.0.0-upgrade-cockpit-connector-SNAPSHOT/gravitee-plugin-4.0.0-upgrade-cockpit-connector-SNAPSHOT.zip)

chore: update cockpit api version

---

gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/internal/AbstractPluginEventListener.java
gravitee-plugin-core/src/test/java/io/gravitee/plugin/core/internal/PluginEventListenerTest.java

**Issue**
https://gravitee.atlassian.net/browse/APIM-4080
Merge the SecretProviderPluginComparator logic into the PluginComparator to respect `Comparator` contract.
---
- use it directly by updating your project with version: `3.1.1-apim-4080-fix-plugin-comparator-3-x-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/plugin/gravitee-plugin/3.1.1-apim-4080-fix-plugin-comparator-3-x-SNAPSHOT/gravitee-plugin-3.1.1-apim-4080-fix-plugin-comparator-3-x-SNAPSHOT.zip)

fix: simplify plugins comparison - 3.x

---

gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/internal/AbstractPluginEventListener.java
gravitee-plugin-core/src/test/java/io/gravitee/plugin/core/internal/PluginEventListenerTest.java

**Issue**
https://gravitee.atlassian.net/browse/APIM-4080
Merge the SecretProviderPluginComparator logic into the PluginComparator to respect `Comparator` contract.
---
- use it directly by updating your project with version: `4.0.3-apim-4080-fix-plugin-comparator-master-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/plugin/gravitee-plugin/4.0.3-apim-4080-fix-plugin-comparator-master-SNAPSHOT/gravitee-plugin-4.0.3-apim-4080-fix-plugin-comparator-master-SNAPSHOT.zip)

fix: simplify plugins comparison - master

---

gravitee-plugin-core/src/test/java/io/gravitee/plugin/core/internal/PluginRegistryTest.java
gravitee-plugin-repository/src/main/java/io/gravitee/plugin/repository/internal/RepositoryPluginHandler.java
gravitee-plugin-repository/src/main/java/io/gravitee/plugin/repository/internal/RepositoryTypeReader.java
gravitee-plugin-repository/src/test/java/io/gravitee/plugin/repository/internal/RepositoryTypeReaderTest.java
pom.xml

solves ARCHI-397
moved to new properties structure. Old approach remained as a fallback option. 
---
- use it directly by updating your project with version: `4.2.0-feature-ARCHI-397-new-repostiory-properties-structure-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/plugin/gravitee-plugin/4.2.0-feature-ARCHI-397-new-repostiory-properties-structure-SNAPSHOT/gravitee-plugin-4.2.0-feature-ARCHI-397-new-repostiory-properties-structure-SNAPSHOT.zip)

ARCHI-397 feat: introduced 'repository.' prefix for its properties.

---

gravitee-plugin-alert/pom.xml
gravitee-plugin-connector/pom.xml
gravitee-plugin-fetcher/pom.xml
gravitee-plugin-notifier/pom.xml
gravitee-plugin-policy/pom.xml
gravitee-plugin-resource/pom.xml
gravitee-plugin-service-discovery/pom.xml
pom.xml

**Issue**
N/A
To allow importing gravitee-plugin in the dependency management section of another project's pom.
---
- use it directly by updating your project with version: `4.2.1-fix-dependency-management-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/plugin/gravitee-plugin/4.2.1-fix-dependency-management-SNAPSHOT/gravitee-plugin-4.2.1-fix-dependency-management-SNAPSHOT.zip)

fix: declare all modules in dependency management

---

gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/api/AbstractConfigurablePluginManager.java
gravitee-plugin-core/src/test/java/io/gravitee/plugin/core/api/AbstractConfigurablePluginManagerTest.java

Shared policy group are not a regular plugin and have neither documentation nor schema, so null check must be properly done

fix: fix resource access for null plugins

---

gravitee-plugin-annotation-processors/README.adoc
gravitee-plugin-annotation-processors/src/main/java/io/gravitee/plugin/annotation/processor/ConfigurationEvaluatorProcessor.java
gravitee-plugin-annotation-processors/src/main/resources/templates/evalField.mustache
gravitee-plugin-annotation-processors/src/main/resources/templates/evaluatorFooter.mustache
gravitee-plugin-annotation-processors/src/main/resources/templates/evaluatorHeader.mustache
gravitee-plugin-annotation-processors/src/test/java/io/gravitee/plugin/annotation/processor/ConfigurationEvaluatorGeneratedTest.java
gravitee-plugin-annotation-processors/src/test/java/io/gravitee/plugin/annotation/processor/result/TestConfiguration.java
gravitee-plugin-annotation-processors/src/test/resources/test/TestConfigurationEvaluator.java

in ConfigurationEvaluatorProcessor (and fix getter generation to use attribute name)
**Issue**
https://gravitee.atlassian.net/browse/APIM-7500
Add EL support for HttpHeader List (gravitee-common) in annotation processor to complete the story on secret for Http Endpoint. Also fix an issue with getter generated based on class name instead of attribute name.
---
- use it directly by updating your project with version: `4.5.0-feat-add-support-httpheader-list-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/plugin/gravitee-plugin/4.5.0-feat-add-support-http …

feat: add EL support for io.gravitee.common.http.HttpHeader List

---

gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/internal/AbstractPluginEventListener.java

this new plugin is only useful for AM but it need to be loaded after the reporitory plugin but before any other plugin
fixes AM-4564
---
- use it directly by updating your project with version: `4.6.0-am-4564-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/plugin/gravitee-plugin/4.6.0-am-4564-SNAPSHOT/gravitee-plugin-4.6.0-am-4564-SNAPSHOT.zip)

feat: declare new plugin type 'data-plane' in the priority list

---

gravitee-plugin-annotation-processors/src/main/resources/templates/evaluatorHeader.mustache
gravitee-plugin-annotation-processors/src/test/java/io/gravitee/plugin/annotation/processor/ConfigurationEvaluatorGeneratedTest.java
gravitee-plugin-annotation-processors/src/test/java/io/gravitee/plugin/annotation/processor/result/TestConfiguration.java
gravitee-plugin-annotation-processors/src/test/resources/test/TestConfigurationEvaluator.java

Fixing NPE on primitive type
---
- use it directly by updating your project with version: `4.6.1-fix-npe-on-primitive-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/plugin/gravitee-plugin/4.6.1-fix-npe-on-primitive-SNAPSHOT/gravitee-plugin-4.6.1-fix-npe-on-primitive-SNAPSHOT.zip)

fix: avoid using primitive type for eval method

---

gravitee-plugin-annotation-processors/src/main/resources/templates/evaluatorHeader.mustache
gravitee-plugin-annotation-processors/src/test/java/io/gravitee/plugin/annotation/processor/result/TestConfiguration.java
gravitee-plugin-annotation-processors/src/test/resources/test/TestConfigurationEvaluator.java

**Issue**
A small description of what you did in that PR.
---
- use it directly by updating your project with version: `4.9.0-mba-double-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/plugin/gravitee-plugin/4.9.0-mba-double-SNAPSHOT/gravitee-plugin-4.9.0-mba-double-SNAPSHOT.zip)

feat: allow to set Double in plugin config
