gravitee-io/gravitee-plugin

- gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/internal/PluginEventListener.java
- gravitee-plugin-fetcher/pom.xml
- gravitee-plugin-fetcher/src/main/java/io/gravitee/plugin/fetcher/FetcherClassLoaderFactory.java
- gravitee-plugin-fetcher/src/main/java/io/gravitee/plugin/fetcher/FetcherPlugin.java
- gravitee-plugin-fetcher/src/main/java/io/gravitee/plugin/fetcher/FetcherPluginManager.java
- gravitee-plugin-fetcher/src/main/java/io/gravitee/plugin/fetcher/internal/FetcherClassLoaderFactoryImpl.java
- gravitee-plugin-fetcher/src/main/java/io/gravitee/plugin/fetcher/internal/FetcherConfigurationClassFinder.java
- gravitee-plugin-fetcher/src/main/java/io/gravitee/plugin/fetcher/internal/FetcherPluginHandler.java
- gravitee-plugin-fetcher/src/main/java/io/gravitee/plugin/fetcher/internal/FetcherPluginImpl.java
- gravitee-plugin-fetcher/src/main/java/io/gravitee/plugin/fetcher/internal/FetcherPluginManagerImpl.java
- gravitee-plugin-fetcher/src/main/java/io/gravitee/plugin/fetcher/spring/FetcherPluginConfiguration.java
- gravitee-plugin-fetcher/src/main/resources/META-INF/spring.factories
- pom.xml
> feat(fetcher): Add fetcher plugin handler

- gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/internal/PluginEventListener.java
- gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/internal/PluginImpl.java
- gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/internal/PluginRegistryImpl.java
- gravitee-plugin-core/src/test/java/io/gravitee/plugin/core/PluginEventListenerTest.java
> feat(plugin): Fail when trying to install an already loaded plugin.

- gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/internal/PluginRegistryConfiguration.java
- gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/internal/PluginRegistryImpl.java
- gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/spring/PluginConfiguration.java
- gravitee-plugin-core/src/test/java/io/gravitee/plugin/core/PluginRegistryTest.java
> feat(plugin): Allow to load plugin from multiple registries

- gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/api/PluginType.java
- gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/internal/PluginEventListener.java
This closes gravitee-io/graviteeio-access-management#171
> feat(extensionGrant) : add extension grant plugin type for Gravitee.io AM

- gravitee-plugin-core/pom.xml
- gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/internal/PluginRegistryImpl.java
- gravitee-plugin-fetcher/pom.xml
- gravitee-plugin-policy/pom.xml
- gravitee-plugin-resource/pom.xml
- pom.xml
Closes gravitee-io/issues#1137
> feat(plugin): Extend the plugin classloader with additional libraries

- gravitee-plugin-policy/src/main/java/io/gravitee/plugin/policy/PolicyPlugin.java
- gravitee-plugin-policy/src/main/java/io/gravitee/plugin/policy/internal/PolicyPluginHandler.java
- gravitee-plugin-policy/src/main/java/io/gravitee/plugin/policy/internal/PolicyPluginImpl.java
Closes gravitee-io/issues#1622
> feat(gateway): Performance improvements

- gravitee-plugin-alert/pom.xml
- gravitee-plugin-alert/src/main/java/io/gravitee/plugin/alert/AlertClassLoaderFactory.java
- gravitee-plugin-alert/src/main/java/io/gravitee/plugin/alert/AlertEngineService.java
- gravitee-plugin-alert/src/main/java/io/gravitee/plugin/alert/AlertPlugin.java
- gravitee-plugin-alert/src/main/java/io/gravitee/plugin/alert/internal/AlertClassLoaderFactoryImpl.java
- gravitee-plugin-alert/src/main/java/io/gravitee/plugin/alert/internal/AlertEngineServiceImpl.java
- gravitee-plugin-alert/src/main/java/io/gravitee/plugin/alert/internal/AlertPluginHandler.java
- gravitee-plugin-alert/src/main/java/io/gravitee/plugin/alert/internal/AlertPluginImpl.java
- gravitee-plugin-alert/src/main/java/io/gravitee/plugin/alert/spring/AlertPluginConfiguration.java
- gravitee-plugin-alert/src/main/resources/META-INF/spring.factories
- gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/internal/PluginEventListener.java
- pom.xml
This closes gravitee-io/issues#63
> feat: allows to send an alert when the HC status changes

- gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/api/AbstractConfigurablePluginManager.java
- gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/api/AbstractPluginManager.java
- gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/api/AbstractSubTypesFinder.java
- gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/api/ConfigurablePluginManager.java
- gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/api/PluginManager.java
- gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/api/PluginType.java
- gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/internal/PluginEventListener.java
- gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/internal/ReflectionBasedPluginConfigurationResolver.java
- gravitee-plugin-fetcher/src/main/java/io/gravitee/plugin/fetcher/internal/FetcherPluginHandler.java
- gravitee-plugin-fetcher/src/main/java/io/gravitee/plugin/fetcher/internal/FetcherPluginManagerImpl.java
- gravitee-plugin-fetcher/src/main/java/io/gravitee/plugin/fetcher/spring/FetcherPluginConfiguration.java
- gravitee-plugin-policy/src/main/java/io/gravitee/plugin/policy/internal/PolicyPluginHandler.java
- gravitee-plugin-policy/src/main/java/io/gravitee/plugin/policy/internal/PolicyPluginManagerImpl.java
- gravitee-plugin-policy/src/main/java/io/gravitee/plugin/policy/spring/PolicyPluginConfiguration.java
- gravitee-plugin-service-discovery/pom.xml
- gravitee-plugin-service-discovery/src/main/java/io/gravitee/plugin/discovery/ServiceDiscoveryClassLoaderFactory.java
- gravitee-plugin-service-discovery/src/main/java/io/gravitee/plugin/discovery/ServiceDiscoveryPlugin.java
- gravitee-plugin-service-discovery/src/main/java/io/gravitee/plugin/discovery/internal/ServiceDiscoveryClassLoaderFactoryImpl.java
- gravitee-plugin-service-discovery/src/main/java/io/gravitee/plugin/discovery/internal/ServiceDiscoveryConfigurationClassFinder.java
- gravitee-plugin-service-discovery/src/main/java/io/gravitee/plugin/discovery/internal/ServiceDiscoveryPluginHandler.java
- gravitee-plugin-service-discovery/src/main/java/io/gravitee/plugin/discovery/internal/ServiceDiscoveryPluginImpl.java
- gravitee-plugin-service-discovery/src/main/java/io/gravitee/plugin/discovery/internal/ServiceDiscoveryPluginManagerImpl.java
- gravitee-plugin-service-discovery/src/main/java/io/gravitee/plugin/discovery/spring/ServiceDiscoveryPluginConfiguration.java
- gravitee-plugin-service-discovery/src/main/resources/META-INF/spring.factories
- pom.xml
Closes gravitee-io/issues#1701
> feat(discovery): Manage service discovery as a plugin

- gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/internal/PluginRegistryConfiguration.java
- gravitee-plugin-core/src/test/java/io/gravitee/plugin/core/PluginEventListenerTest.java
- pom.xml
> chore: Java 11 support

- gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/internal/AnnotationBasedPluginContextConfigurer.java
- gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/internal/PluginContextFactoryImpl.java
- gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/internal/PluginRegistryImpl.java
Closes gravitee-io/issues#1311
> feat(eureka): Add support for Spring Core

- gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/internal/PluginContextFactoryImpl.java
This closes gravitee-io/issues#2116
> fix: No suitable driver with any JDBC driver

- gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/api/PluginType.java
- gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/internal/PluginEventListener.java
closes gravitee-io/issues#2185
> chore(): add PROTOCOL Plugin Type for AM gateway

- gravitee-plugin-alert/src/main/java/io/gravitee/plugin/alert/internal/AlertPluginHandler.java
- gravitee-plugin-api/pom.xml
- gravitee-plugin-api/src/main/java/io/gravitee/plugin/api/DeploymentContext.java
- gravitee-plugin-api/src/main/java/io/gravitee/plugin/api/DeploymentLifecycle.java
- gravitee-plugin-api/src/main/java/io/gravitee/plugin/api/annotations/Plugin.java
- gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/api/AbstractPluginHandler.java
- gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/api/AbstractSimplePluginHandler.java
- gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/api/AbstractSpringPluginHandler.java
- gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/api/AbstractSubTypesFinder.java
- gravitee-plugin-fetcher/src/main/java/io/gravitee/plugin/fetcher/internal/FetcherPluginHandler.java
- gravitee-plugin-notifier/src/main/java/io/gravitee/plugin/notifier/internal/NotifierPluginHandler.java
- gravitee-plugin-policy/src/main/java/io/gravitee/plugin/policy/internal/PolicyPluginHandler.java
- gravitee-plugin-resource/src/main/java/io/gravitee/plugin/resource/internal/ResourcePluginHandler.java
- gravitee-plugin-service-discovery/src/main/java/io/gravitee/plugin/discovery/internal/ServiceDiscoveryPluginHandler.java
- pom.xml
Closes gravitee-io/issues#2880
> feat(plugin): Add deployment interceptor to plugins

- gravitee-plugin-repository/pom.xml
- gravitee-plugin-repository/src/main/java/io/gravitee/plugin/repository/internal/RepositoryPluginHandler.java
- gravitee-plugin-repository/src/main/resources/META-INF/spring.factories
- pom.xml
Closes gravitee-io/issues#3141
> feat(repository): Add a unified RepositoryPluginHandler

- gravitee-plugin-repository/src/main/java/io/gravitee/plugin/repository/internal/RepositoryPluginHandler.java
Closes gravitee-io/issues#3190
> fix(log): Fix wrong log parameter order

- gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/api/PluginType.java
- gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/internal/PluginEventListener.java
closes gravitee-io/issues#3125
> chore: add new Factor plugin type

- gravitee-plugin-identityprovider/pom.xml
- gravitee-plugin-identityprovider/src/main/java/io/gravitee/plugin/identityprovider/IdentityProviderPluginHandler.java
- gravitee-plugin-identityprovider/src/main/resources/META-INF/spring.factories
- pom.xml
Closes gravitee-io/issues#3232
> feat(identity-provider): Add IdentityProvider plugin handler

- pom.xml
> fix(alert): move to api 1.3.0

- gravitee-plugin-policy/src/main/java/io/gravitee/plugin/policy/PolicyPlugin.java
- gravitee-plugin-policy/src/main/java/io/gravitee/plugin/policy/internal/PolicyContextClassFinder.java
- gravitee-plugin-policy/src/main/java/io/gravitee/plugin/policy/internal/PolicyPluginHandler.java
- gravitee-plugin-policy/src/main/java/io/gravitee/plugin/policy/internal/PolicyPluginImpl.java
- pom.xml
Closes gravitee-io/issues#3935
> feat(policy-context): add policy context capability

- pom.xml
> feat(management): auto fetch pages based on user configuration

- gravitee-plugin-alert/src/main/java/io/gravitee/plugin/alert/AlertPlugin.java
- gravitee-plugin-alert/src/main/java/io/gravitee/plugin/alert/internal/AlertPluginHandler.java
- gravitee-plugin-cockpit/src/main/java/io/gravitee/plugin/cockpit/CockpitPluginHandler.java
- gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/api/AbstractConfigurablePluginManager.java
- gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/api/ConfigurablePlugin.java
- gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/api/Plugin.java
- gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/api/PluginManager.java
- gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/api/PluginManifest.java
- gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/api/PluginRegistry.java
- gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/internal/AnnotationBasedPluginContextConfigurer.java
- gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/internal/PluginEventListener.java
- gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/internal/PluginImpl.java
- gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/internal/PluginManifestProperties.java
- gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/internal/PluginRegistryImpl.java
- gravitee-plugin-core/src/test/java/io/gravitee/plugin/core/PluginEventListenerTest.java
- gravitee-plugin-fetcher/src/main/java/io/gravitee/plugin/fetcher/FetcherPlugin.java
- gravitee-plugin-fetcher/src/main/java/io/gravitee/plugin/fetcher/internal/FetcherPluginHandler.java
- gravitee-plugin-identityprovider/src/main/java/io/gravitee/plugin/identityprovider/IdentityProviderPluginHandler.java
- gravitee-plugin-notifier/src/main/java/io/gravitee/plugin/notifier/NotifierPlugin.java
- gravitee-plugin-notifier/src/main/java/io/gravitee/plugin/notifier/internal/NotifierPluginHandler.java
- gravitee-plugin-policy/src/main/java/io/gravitee/plugin/policy/PolicyPlugin.java
- gravitee-plugin-policy/src/main/java/io/gravitee/plugin/policy/internal/PolicyPluginHandler.java
- gravitee-plugin-repository/src/main/java/io/gravitee/plugin/repository/internal/RepositoryPluginHandler.java
- gravitee-plugin-resource/src/main/java/io/gravitee/plugin/resource/ResourcePlugin.java
- gravitee-plugin-resource/src/main/java/io/gravitee/plugin/resource/internal/ResourcePluginHandler.java
- gravitee-plugin-service-discovery/src/main/java/io/gravitee/plugin/discovery/ServiceDiscoveryPlugin.java
- gravitee-plugin-service-discovery/src/main/java/io/gravitee/plugin/discovery/internal/ServiceDiscoveryPluginHandler.java
Closes gravitee-io/issues#4123
> feat(plugin): Add support for plugin icon and documentation

- gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/api/AbstractPluginHandler.java
- gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/api/AbstractSpringPluginHandler.java
- gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/api/PluginHandler.java
- gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/internal/AnnotationBasedPluginContextConfigurer.java
- gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/internal/PluginEventListener.java
Closes gravitee-io/issues#4486
> fix: Ensure repository is loaded first

- gravitee-plugin-repository/src/main/java/io/gravitee/plugin/repository/internal/RepositoryPluginHandler.java
closes gravitee-io/issues#4834
> fix(repository): check repository type before loading the repository implementations

- gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/api/AbstractConfigurablePluginManager.java
> fix: resolve SVG mimeType with oracle JDK 11.0.2

- .circleci/config.yml
- gravitee-plugin-cockpit/src/main/java/io/gravitee/plugin/cockpit/CockpitPluginHandler.java
- pom.xml
**Issue**
Related to https://github.com/gravitee-io/issues/issues/5526
Register `CockpitConnector` bean to be able to autowire it in APIM/AM.
> Register `CockpitConnector` bean to be able to autowire it in APIM/AM

- gravitee-plugin-identityprovider/src/main/java/io/gravitee/plugin/identityprovider/IdentityProviderPluginHandler.java
Currently all the identity providers are handled. We need to check if the idp is enabled or not to avoid having warn logs when it's not configured because disabled.
> refactor: check if an idp is enabled.

- gravitee-plugin-alert/pom.xml
- gravitee-plugin-api/pom.xml
- gravitee-plugin-api/src/main/java/io/gravitee/plugin/api/PluginDeploymentContext.java
- gravitee-plugin-api/src/main/java/io/gravitee/plugin/api/PluginDeploymentContextFactory.java
- gravitee-plugin-api/src/main/java/io/gravitee/plugin/api/PluginDeploymentLifecycle.java
- gravitee-plugin-api/src/main/java/io/gravitee/plugin/api/annotations/Plugin.java
- gravitee-plugin-cockpit/pom.xml
- gravitee-plugin-connector/pom.xml
- gravitee-plugin-core/pom.xml
- gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/api/AbstractPluginHandler.java
- gravitee-plugin-fetcher/pom.xml
- gravitee-plugin-identityprovider/pom.xml
- gravitee-plugin-notifier/pom.xml
- gravitee-plugin-policy/pom.xml
- gravitee-plugin-repository/pom.xml
- gravitee-plugin-resource/pom.xml
- gravitee-plugin-service-discovery/pom.xml
- pom.xml
**Issue**
A small description of what you did in that PR.
---
- use it directly by updating your project with version: `1.23.0-refactor-ce-ee-bundle-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/plugin/gravitee-plugin/1.23.0-refactor-ce-ee-bundle-SNAPSHOT/gravitee-plugin-1.23.0-refactor-ce-ee-bundle-SNAPSHOT.zip)
> refactor: Single distribution bundle for CE / EE

- gravitee-plugin-policy/src/main/java/io/gravitee/plugin/policy/internal/PolicyMethodResolver.java
- gravitee-plugin-policy/src/test/java/io/gravitee/plugin/policy/PolicyMethodResolverTest.java
- pom.xml
Allows to detect policy annotations from parent class
> feat(jupiter): detect inherited policy methods

- gravitee-plugin-alert/pom.xml
- gravitee-plugin-api/pom.xml
- gravitee-plugin-cockpit/pom.xml
- gravitee-plugin-connector/pom.xml
- gravitee-plugin-core/pom.xml
- gravitee-plugin-fetcher/pom.xml
- gravitee-plugin-identityprovider/pom.xml
- gravitee-plugin-notifier/pom.xml
- gravitee-plugin-policy/pom.xml
- gravitee-plugin-repository/pom.xml
- gravitee-plugin-resource/pom.xml
- gravitee-plugin-service-discovery/pom.xml
Wrong version was set on child sub modules
> fix: fix version for all sub-modules

- gravitee-plugin-alert/pom.xml
- gravitee-plugin-api/pom.xml
- gravitee-plugin-cockpit/pom.xml
- gravitee-plugin-connector/pom.xml
- gravitee-plugin-core/pom.xml
- gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/api/PluginType.java
- gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/internal/PluginEventListener.java
- gravitee-plugin-fetcher/pom.xml
- gravitee-plugin-identityprovider/pom.xml
- gravitee-plugin-notifier/pom.xml
- gravitee-plugin-policy/pom.xml
- gravitee-plugin-repository/pom.xml
- gravitee-plugin-resource/pom.xml
- gravitee-plugin-service-discovery/pom.xml
- pom.xml
**Issue**
https://gravitee.atlassian.net/browse/ARCHI-231
Following the work done on cluster, now make cache manager as plugin.
> feat: add new cache plugin

- gravitee-plugin-alert/pom.xml
- gravitee-plugin-api/pom.xml
- gravitee-plugin-cockpit/pom.xml
- gravitee-plugin-connector/pom.xml
- gravitee-plugin-core/pom.xml
- gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/internal/AnnotationBasedPluginContextConfigurer.java
- gravitee-plugin-fetcher/pom.xml
- gravitee-plugin-identityprovider/pom.xml
- gravitee-plugin-notifier/pom.xml
- gravitee-plugin-policy/pom.xml
- gravitee-plugin-repository/pom.xml
- gravitee-plugin-repository/src/main/java/io/gravitee/plugin/repository/internal/RepositoryPluginHandler.java
- gravitee-plugin-resource/pom.xml
- gravitee-plugin-service-discovery/pom.xml
- pom.xml
**Issue**
https://gravitee.atlassian.net/browse/ARCHI-217
Fix an issue with classloading and add support of optional scope
> Archi 217 distributed sync

- gravitee-plugin-repository/src/main/java/io/gravitee/plugin/repository/internal/RepositoryPluginHandler.java
see https://gravitee.atlassian.net/browse/APIM-1685
---
- use it directly by updating your project with version: `2.0.0-deployable-repositories-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/plugin/gravitee-plugin/2.0.0-deployable-repositories-SNAPSHOT/gravitee-plugin-2.0.0-deployable-repositories-SNAPSHOT.zip)
> feat: allow to deploy repositories based on license

- gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/internal/PluginEventListener.java
- gravitee-plugin-core/src/test/java/io/gravitee/plugin/core/internal/PluginEventListenerTest.java
**Issue**
https://gravitee.atlassian.net/browse/APIM-4080
Merge the SecretProviderPluginComparator logic into the PluginComparator to respect `Comparator` contract.
---
- use it directly by updating your project with version: `2.2.2-apim-4080-fix-plugin-comparator-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/plugin/gravitee-plugin/2.2.2-apim-4080-fix-plugin-comparator-SNAPSHOT/gravitee-plugin-2.2.2-apim-4080-fix-plugin-comparator-SNAPSHOT.zip)
> fix: simplify plugins comparison - 2.x

- gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/api/PluginType.java
- gravitee-plugin-core/src/main/java/io/gravitee/plugin/core/internal/PluginRegistryImpl.java
- gravitee-plugin-integrationprovider/pom.xml
- gravitee-plugin-integrationprovider/src/main/java/io/gravitee/plugin/integrationprovider/IntegrationProviderClassLoaderFactory.java
- gravitee-plugin-integrationprovider/src/main/java/io/gravitee/plugin/integrationprovider/IntegrationProviderPlugin.java
- gravitee-plugin-integrationprovider/src/main/java/io/gravitee/plugin/integrationprovider/IntegrationProviderPluginManager.java
- gravitee-plugin-integrationprovider/src/main/java/io/gravitee/plugin/integrationprovider/internal/DefaultIntegrationProviderClassLoaderFactory.java
- gravitee-plugin-integrationprovider/src/main/java/io/gravitee/plugin/integrationprovider/internal/DefaultIntegrationProviderPlugin.java
- gravitee-plugin-integrationprovider/src/main/java/io/gravitee/plugin/integrationprovider/internal/DefaultIntegrationProviderPluginManager.java
- gravitee-plugin-integrationprovider/src/main/java/io/gravitee/plugin/integrationprovider/internal/IntegrationProviderConfigurationClassFinder.java
- gravitee-plugin-integrationprovider/src/main/java/io/gravitee/plugin/integrationprovider/internal/IntegrationProviderPluginHandler.java
- gravitee-plugin-integrationprovider/src/main/java/io/gravitee/plugin/integrationprovider/spring/IntegrationProviderPluginConfiguration.java
- gravitee-plugin-integrationprovider/src/main/resources/META-INF/spring.factories
- pom.xml
Issue
https://gravitee.atlassian.net/browse/ARCHI-294
Description
New plugin handler IntegrationProvider to allow creating plugins for each provider needed for integration/federation.
> feat: add new integration provider plugin type

- .circleci/config.yml
- pom.xml
**Issue**
A small description of what you did in that PR.
---
- use it directly by updating your project with version: `4.9.0`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/plugin/gravitee-plugin/4.9.0/gravitee-plugin-4.9.0.zip)
> chore: updates parents
